github_url = "{{ cookiecutter.repo_url }}"

[version]
current = "{{ cookiecutter.version }}"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

{%- if cookiecutter.use_poetry == "y" %}
[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'
{% endif %}

[[file]]
src = "beet-release.json"

{% if cookiecutter.datapack == "y" -%}
[[file]]
src = "datapack/data/{{cookiecutter.datapack_namespace}}/functions/{{cookiecutter.project_namespace}}/load.mcfunction"

[[file]]
src = "datapack/data/{{cookiecutter.datapack_namespace}}/functions/{{cookiecutter.project_namespace}}/install.mcfunction"

[[file]]
src = "datapack/data/{{cookiecutter.datapack_namespace}}/advancements/{{cookiecutter.project_namespace}}/root.json"
{%- endif %}